newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡


  Thank you and congrats🎉 for opening your very first issue in this project. AI Interview project is built with OpenCV, Keras/TensorFlow using Deep Learning and Computer Vision concepts in order to detect face/audio emotion in static images or WAV as well as in real-time video streams.
  Please adhere to our [Code of Conduct](https://github.com/aryasoni98/AI-Interview/blob/master/CODE_OF_CONDUCT.md).
  Please make sure not to start working on the issue, unless you get assigned to it.😄

newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖


  Thank you and congrats🎉 for opening your first pull request. AI Interview project is built with OpenCV, Keras/TensorFlow using Deep Learning and Computer Vision concepts in order to detect face/audio emotion in static images or WAV as well as in real-time video streams.
  Please adhere to our [Code of Conduct](https://github.com/aryasoni98/AI-Interview/blob/master/CODE_OF_CONDUCT.md).🙌 We will get back to you as soon as we can 😄.

firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀.
